#include "PCH.h"
#include "Config.h"
#include "GameStatePoller.h"
#include "WebSocketServer.h"

#include <REX/LOG.h>

// F4SEPlugin_Version is auto-generated by the commonlibf4.plugin XMake rule
// from res/commonlibf4-plugin.cpp.in — do NOT define it here.

namespace PipBoyRemote
{
    // Handles lifecycle events broadcast by the F4SE messaging interface.
    // Called on the game main thread.
    static void OnF4SEMessage(F4SE::MessagingInterface::Message* msg) noexcept
    {
        if (!msg) { return; }

        switch (msg->type) {
            case F4SE::MessagingInterface::kGameLoaded:
            case F4SE::MessagingInterface::kNewGame:
                // A save has been loaded or a new game has started — begin polling
                // and (re-)open the WebSocket server if it is not already running.
                GameStatePoller::GetSingleton().Start();
                WebSocketServer::GetSingleton().Start();
                break;

            case F4SE::MessagingInterface::kPreLoadGame:
                // Pause sampling while the game engine loads world data.
                GameStatePoller::GetSingleton().Pause();
                break;

            case F4SE::MessagingInterface::kPostLoadGame:
                // World data is ready — resume normal polling.
                GameStatePoller::GetSingleton().Resume();
                break;

            case F4SE::MessagingInterface::kPreSaveGame:
                // Nothing to do — saves do not affect the server or poller.
                break;

            default:
                break;
        }
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Plugin entry point
// ──────────────────────────────────────────────────────────────────────────────

F4SE_PLUGIN_LOAD(const F4SE::LoadInterface* a_f4se)
{
    F4SE::Init(a_f4se);

    // Reject editor mode — this plugin is runtime-only.
    if (a_f4se->IsEditor()) {
        REX::WARN("[PipBoyRemote] Running in editor mode — plugin disabled");
        return true;
    }

    // Load INI settings (falls back to defaults if the file is missing).
    const auto config = PipBoyRemote::Config::Load();

    if (!config.enabled) {
        REX::INFO("[PipBoyRemote] Disabled via INI (PipBoyRemote.Enable=0)");
        return true;
    }

    // Configure the WebSocket server before any game events arrive.
    PipBoyRemote::WebSocketServer::GetSingleton().Initialize(config);

    // Register the permanent per-frame polling task.
    // This is a no-op if called more than once (guarded by an atomic flag).
    PipBoyRemote::GameStatePoller::GetSingleton().Register();

    // Subscribe to F4SE lifecycle events.
    const auto* messaging = F4SE::GetMessagingInterface();
    if (!messaging) {
        REX::ERROR("[PipBoyRemote] F4SE messaging interface unavailable");
        return false;
    }
    messaging->RegisterListener(PipBoyRemote::OnF4SEMessage);

    REX::INFO(
        "[PipBoyRemote] Loaded — WebSocket server will start on {}:{}",
        config.bindIP, config.port
    );
    return true;
}
